name: chat_engine
services:
  vllm:
    image: vllm/vllm-openai:v0.13.0 # v0.10.0 for smaller size
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all          # or change to 1, or list device_ids
              capabilities: [gpu]
              options:
                runtime: nvidia
    ports:
      - "${SERVING_LLM_PORT:-8100}:8000"
    volumes:
      - vllm-cache:/root/.cache/huggingface/hub
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISABLE_UVICORN_PROPAGATION=true
      - VLLM_USE_V1=1
    command: >
      --model ${LLM_MODEL_NAME:-Qwen/Qwen3-4B-AWQ}
      --max-model-len ${MAX_MODEL_LEN:-16384}
      --max-num-seqs ${NUM_SEQS:-16}
      --max-num-batched-tokens ${BATCHED_TOKENS:-4096}
      --enforce-eager
      --quantization awq_marlin
      --gpu-memory-utilization ${GPU_MEM_UTIL:-0.8}
      --api-key ${SERVING_API_KEY:-token}

volumes:
  vllm-cache:
    driver: local